export const colorPalettes = [
  "maroon",
  "red",
  "pink",
  "soft-pink",
  "blue",
  "emerald",
  "yellow",
  "zinc",
] as const;

export const colorShades = [
  "50",
  "100",
  "200",
  "300",
  "400",
  "500",
  "600",
  "700",
  "800",
  "900",
  "950",
] as const;

export const semanticGroups = [
  {
    name: "background",
    tokens: [
      "plain",
      "subtle",
      "muted",
      "soft",
      "default",
      "inverse",
      "elevated",
      "overlay",
      "primary",
      "primary-saturated",
      "primary-faint",
      "primary-fade",
      "info",
      "info-faint",
      "info-fade",
      "secondary",
      "secondary-faint",
      "secondary-fade",
      "success",
      "success-faint",
      "success-fade",
      "warning",
      "warning-faint",
      "warning-fade",
      "danger",
      "danger-saturated",
      "danger-faint",
      "danger-fade",
    ],
  },
  {
    name: "text",
    tokens: [
      "plain",
      "subtle",
      "muted",
      "soft",
      "default",
      "inverse",
      "primary",
      "primary-faint",
      "primary-fade",
      "info",
      "info-faint",
      "info-fade",
      "secondary",
      "secondary-faint",
      "secondary-fade",
      "success",
      "success-faint",
      "success-fade",
      "warning",
      "warning-faint",
      "warning-fade",
      "danger",
      "danger-faint",
      "danger-fade",
    ],
  },
  {
    name: "border",
    tokens: [
      "plain",
      "subtle",
      "muted",
      "soft",
      "default",
      "inverse",
      "primary",
      "primary-faint",
      "primary-fade",
      "info",
      "info-faint",
      "info-fade",
      "secondary",
      "secondary-faint",
      "secondary-fade",
      "success",
      "success-faint",
      "success-fade",
      "warning",
      "warning-faint",
      "warning-fade",
      "danger",
      "danger-faint",
      "danger-fade",
    ],
  },
] as const;

export const effectTokens = {
  shadows: [
    "shadow-subtle-sm",
    "shadow-subtle",
    "shadow-subtle-lg",
    "shadow-soft-sm",
    "shadow-soft",
    "shadow-soft-lg",
  ],
  rings: ["ring-default", "ring-danger"],
  radius: ["rounded-sm", "rounded-base", "rounded-lg", "rounded-xl"],
} as const;

export const typographyScale = [
  ["Display 2XL", "72px", "text-display-2xl"],
  ["Display XL", "60px", "text-display-xl"],
  ["Display LG", "48px", "text-display-lg"],
  ["Display MD", "36px", "text-display-md"],
  ["Display SM", "30px", "text-display-sm"],
  ["Heading LG", "24px", "text-heading-lg"],
  ["Heading MD", "20px", "text-heading-md"],
  ["Body LG", "18px", "text-body-lg"],
  ["Body", "16px", "text-body"],
  ["Body SM", "14px", "text-body-sm"],
  ["Caption", "12px", "text-caption"],
] as const;
