import type { Metadata } from "next";
import { Geist, Geist_Mono, Sarabun, Tajawal } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/shared/themes/them-provider';
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Providers from "@/shared/providers/global/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sarabun = Sarabun({
  subsets: ['latin' , 'thai'],
  weight: ['400', '500' , '600', '700'],
  variable: '--font-sarabun'
});

const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: ['400', '500', '700', '800'],
  variable: '--font-tajawal'

});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props  {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};

export default async function LocaleLayout({children, params}: Props) {

 const paramsResalt = await params
 const local = paramsResalt.locale

 const {locale} = await params;
 if (!hasLocale(routing.locales, locale)) {
   notFound();
 }

 const fontClassSwitches = local === 'ar' ? tajawal.variable : sarabun.variable ;

  return (
    <html
      suppressHydrationWarning
      lang={local}
      dir={local === 'ar' ? 'rtl' : 'ltr'}
      className={fontClassSwitches}
      // className={`${geistSans.variable} ${geistMono.variable} ${sarabun.variable} ${tajawal.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning
        className="min-h-full flex flex-col">
       <Providers>
          <ThemeProvider attribute='data-theme' defaultTheme='system' enableSystem disableTransitionOnChange storageKey='theme'>
              {children}
          </ThemeProvider>
       </Providers>
        </body>
    </html>
  );
}
